dev: false
dev_project_path: /home/studio-lab-user/sagemaker-studiolab-notebooks/workspace/hii_operation/
last_update: '2022-07-10'
project_path: /home/studio-lab-user/sagemaker-studiolab-notebooks/workspace/hii_operation/
simidx_last_update: '2022-07-10'
