annual_rainfall_file: TMD_idw_annual_rainfall_2019.csv
dev: false
dev_project_path: /home/ubuntu/workspace/hii-operation-script/
last_update: '2022-07-11'
mm_model_last_update: '2022-07-11'
project_path: /home/ubuntu/workspace/hii-operation-script/
simidx_last_update: '2022-07-11'
station_location_file: TMD-station-meta2021.xlsx
station_rainfall_file: tmd_station.csv
station_value_last_update: '2022-07-11'
