dev: false
dev_project_path: /Users/puri/Documents/workspace/hii-operation-script/
last_update: '2022-07-10'
project_path: /Users/puri/Documents/workspace/hii-operation-script/
simidx_last_update: null
annual_rainfall_file: 'TMD_idw_annual_rainfall_2019.csv'